### ISSUE TITLE
(M5) SEO Optimisation

### ISSUE THREAD

**Issue by SimonMoynihan33** [SimonMoynihan33/KVRN-Apparel#19]
**As a** store owner, **I would like** to optimize my website for search engines so that customers can easily find KVRN through Google and other search platforms.

**Acceptance Criteria**:
- [x] The website follows SEO best practices.
- [x] Meta tags are added.
- [x] robots.txt file is present for crawlers.
- [x] sitemap.xml file is present in the footer.
