### ISSUE TITLE
(M1) Entity Relationship Diagram 

### ISSUE THREAD

**Issue by SimonMoynihan33** [SimonMoynihan33/KVRN-Apparel#22]
**As a** developer, **I would like** to create an ERD for the database so that I can map out the relationships between entities in the project.

**Acceptance Criteria**:
- [x] An ERD is created outlining product, user, and order relationships.
- [x] The ERD reflects database structure and supports business logic.
- [x] Three custom models are planned for implementation.
