### ISSUE TITLE
(M3) Product Review System

### ISSUE THREAD

**Issue by SimonMoynihan33** [SimonMoynihan33/KVRN-Apparel#30]
**As a** customer, **I would like** to leave reviews on products so that I can share my opinions with other buyers.

**Acceptance Criteria**:
- [x] Customers can leave a star rating on products.
- [x] Products are dynamically updated with the average of all ratings of that product.
- [x] Shop products that have been removed cannot be rated, but the order can still be viewed.
